DATA:
  data_name: toscannet
  data_root: # location of data
  split_root: # location of split files (meta_data of TO-scannet)
  classes: 73
  fea_dim: 3
  voxel_size: 0.004
  voxel_max: 80000
  loop: 1
  repeat: False

TRAIN:
  arch: pointtransformer_seg
  use_xyz: True
  sync_bn: False # adopt sync_bn or not
  ignore_label: 255
  train_gpu:  # [0, 1, 2, 3]
  workers: 16  # data loader workers
  batch_size: 16  # batch size for training
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.5
  epochs: 100
  start_epoch: 0
  step_epoch: 30
  multiplier: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  drop_rate: 0.5
  manual_seed:
  print_freq: 50
  save_freq: 1
  save_path:
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  split: val  # use val or test
  test_gpu: [0]
  test_workers: 4
  batch_size_test: 4
  model_path:
  save_folder:
  names_path: data/toscannet_names.txt
