resume: True
method: heatmap
weight: ./checkpoints/TO-crowrd_heatmap_1121/model_best.pth
exp_name: TO-crowrd_heatmap_1121_result
device:
  use_gpu: True
  gpu_ids: "3"
data:
  dataset: TOS_desk
  data_dir: ./data/TO-crowd-wHM
  use_color: False
  use_height: True
  use_aug: True
  batch_size: 8
  num_workers: 8
  ap_iou_thresh: 0.25
  npoints: 40000
model:
  input_feature_dim: 1
other:
  nepoch: 100
  model_save_interval: 1
  model_save_dir: ./checkpoints
  dump_result: True
  dump_interval: 1000
  test_interval: 10