DATA:
  data_name: toscan
  data_root: dataset/toscan/scene-level
  split_root: data/toscan
  classes: 73
  fea_dim: 3
  voxel_size: 0.04
  voxel_max: 80000
  loop: 10
  repeat: False

TRAIN:
  arch: pointtransformer_seg26
  use_xyz: True
  sync_bn: True # adopt sync_bn or not
  ignore_label: 255
  train_gpu: [2, 3] # [0, 1, 2, 3]
  workers: 16  # data loader workers
  batch_size: 16  # batch size for training
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.5
  epochs: 120
  start_epoch: 0
  step_epoch: 30
  multiplier: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  drop_rate: 0.5
  manual_seed:
  print_freq: 50
  save_freq: 1
  save_path:
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  split: val  # split in [train, val and test]
  test_gpu: [0]
  test_workers: 4
  batch_size_test: 4
  model_path:
  save_folder:
  names_path: data/toscan/toscan_all_names.txt
